### PR TITLE
Bridgewaters.HW01

### PR DESCRIPTION
**Pull request by sbridgewaters**
I had difficulties including the picture initially. The GitHub Markdo…wn tutorial had text within the brackets for inserting a picture, but the text did not show (which is what I wanted). It took a bit too long for me to realize that I could just leave it empty.

Doing the list and text emphasis was pretty straightforward and relatively intuitive.

### CODE REVIEW

**Comment by sanjanasarathy** [comment]
Evaluation HW-01
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |    x       |              |            |
| **Presentation**            |         x  |              |            |
| **Achievement, creativity** |           |      x        |            |
| **Ease of access**          |     x      |              |            |

Remarks:

* Great job on the assignment! I liked the link to your birthplace and the incorporation of the list of goals 
* I didn't realize you don't have to name the picture you want to incorporate and instead can just use: ![]
* For the future, you could incorporate headings using the # Heading or ## Subheading syntax to add more structure to the publication

**Comment by nnickels** [comment]
Evaluation HW-01 for Sarah Bridgewaters
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     X      |              |            |
| **Coding strategy**         |     X      |              |            |
| **Presentation**            |     X      |              |            |
| **Achievement, creativity** |           |      X       |            |
| **Ease of access**          |     X      |              |            |

Remarks:

* Great job! Your readme looks good and you've mastered multiple new markdown elements.
* It does take some intuition to realize the alt text doesn't show up - there are a few ways you can add text to your image simply as a colon beforehand or to appear as scroll over text for your reader: [see here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

**Review by nnickels — COMMENTED** [review]
Evaluation HW-01 for Sarah Bridgewaters
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     X     |              |            |
| **Coding strategy**         |     X      |              |            |
| **Presentation**            |     X      |              |            |
| **Achievement, creativity** |           |      X      |            |
| **Ease of access**          |     X     |              |            |

**Comment by diegocardenas1** [comment]
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      x      |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |           |       x       |            |
| **Achievement, creativity** |           |       x       |            |
| **Ease of access**          |      x     |              |            |

* The coding was great and I loved the picture!
* You included a bunch of different markdown elements very concisely.
* It would be cool to see more use of the headings feature in the bio so that it looks a bit more segmented.

**Pull request closed without merging**
