### PR TITLE
Laura Mulholland hw01

### PR DESCRIPTION
**Pull request by lmulholland42**
Laura Mulholland hw01

### CODE REVIEW

**Review by simonys — COMMENTED** [review]
Evaluation HW-01 for Laura Mulholland

Coding Style: N/A
Coding Strategy: N/A
Presentation: Needs Work
Achievement/Creativity: Needs Work
Ease of Access: Satisfactory

Remarks:
       - It looks like you may have struggled with the interfaces and functionality with git and/or R studio. While you are aware of the markdown documentation, you didn't alter the README, except for a simple change in one character that didn't do much to the document.

* Some specific praise?
       - Congratulations on getting it all working!

* Something I learned?
       - Sorry, I didn't learn much from this.

* Specific constructive criticism?
       - It would be helpful in the future to write what you did in the description space when you commit as opposed to the title. This will make it easier for peer reviewers to read in the future

* Something I know and that you, my peer, might like to know because it is relevant to something you struggled with.
       - It's hard to identify what you struggled with from this, but as this is my second time learning git, it still feels just as complicated as the first time, so don't worry about it too much!

**Comment by cernhofer** [comment]
Evaluation HW-01 for Laura Mulholland
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      x     |              |           |
| **Coding strategy**         |           |      x        |           |
| **Presentation**            |           |      x        |           |
| **Achievement, creativity** |           |       x       |           |
| **Ease of access**          |           |        x      |           |

* It looks like you may have not quite finished the workflow- especially in adding, committing, and pushing your changes. Come and talk to me or another TA/Dr. Soltoff if this is the case and we'll see what went wrong and maybe get you some additional points. 
* ***Revised: your readme looks good- there are a few errors (like your picture not rendering and some headers not displaying properly), but you were able to implement a number of markdown elements. Good work!

**Comment by whymand** [comment]
Evaluation HW-01 for Laura Mulholland
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |              |       x     |
| **Coding strategy**         |           |              |     x       |
| **Presentation**            |           |              |       x     |
| **Achievement, creativity** |           |              |     x       |
| **Ease of access**          |           |              |       x     |

Remarks:
 The changes you describe in your initial comment (bold emphasis, headings, list, image) would fulfill the criteria for the assignment. Unfortunately, as the other reviewers mention, it seems as if there was an issue with committing and pushing the changes to GitHub. I can see only that one minor insertion was made to the readme.md file. In general, for future homework assignments, I would recommend periodically checking the GitHub website to make sure the changes you are making in the readme.md file are visible on the website. I would also echo the recommendation of the other reviewer to ask for assistance from a TA in mastering the commit/pull process. Above all, don't be discouraged! I also struggled with the commit/pull issue at first, but was able to resolve it after receiving assistance from a TA.

**Review by whymand — COMMENTED** [review]
Evaluation HW-01 for Laura Mulholland
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |              |       x     |
| **Coding strategy**         |           |              |     x       |
| **Presentation**            |           |              |       x     |
| **Achievement, creativity** |           |              |     x       |
| **Ease of access**          |           |              |       x     |

Remarks:
 The changes you describe in your initial comment (bold emphasis, headings, list, image) would fulfill the criteria for the assignment. Unfortunately, as the other reviewers mention, it seems as if there was an issue with committing and pushing the changes to GitHub. I can see only that one minor insertion was made to the readme.md file. In general, for future homework assignments, I would recommend periodically checking the GitHub website to make sure the changes you are making in the readme.md file are visible on the website. I would also echo the recommendation of the other reviewer to ask for assistance from a TA in mastering the commit/pull process. Above all, don't be discouraged! I also struggled with the commit/pull issue at first, but was able to resolve it after receiving assistance from a TA.

**Pull request closed without merging**
