### PR TITLE
Submission HW 1

### PR DESCRIPTION
**Pull request by soohyun1995**
I had some troubles using markdown. For instance, I realized that I had to make sure to have space between # and the sentences in order to make it work. Moreover, when I was trying to create a list, I assumed that I should write 1.,2.,3.,4., but I realized that I should just write 1. before each item as shown in the website. Finally, I found it confusing to upload an image because I was not sure what to write on Rstudio in replacement of "(/images/logo.png)". 

I found it quite straightforward to commit my changes and push the commit to Github. Instructions on our class website were very helpful.

### CODE REVIEW

**Comment by cernhofer** [comment]
Evaluation HW-01 for soohyun1995
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      x     |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |        x   |              |            |
| **Achievement, creativity** |           |       x       |            |
| **Ease of access**          |       x    |              |            |

* Great work! You were able to implement a number of cool Markdown elements and generated a nice looking readme file.

**Comment by jvallee97** [comment]
Evaluation HW-01 for soohyun1995
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |    X       |              |            |
| **Coding strategy**         |    X       |              |            |
| **Presentation**            |   X        |              |            |
| **Achievement, creativity** |     X      |              |            |
| **Ease of access**          |    X       |              |            |

Seems like you have a full mastery of homework 01. You didn't include a link (not that you needed to) using markdown. If you want to here is how you would 

[I'm an inline-style link](https://www.google.com)

"I'm an inline-style link" would appear and clicking it would direct you to youtube.

**Comment by jvallee97** [comment]
Forgot that my comment will be rendered with markdown, if you want to see the format just look at my comment with raw source.

**Comment by estech01** [comment]
Review for soohyun1995 - HW 01

Coding Style: Excellent
Coding Strategy: Excellent
Presentation: Excellent
Creativity: Satisfactory
Ease of Access: Excellent

Sara, this looks really great. I liked the way you used headers to break up the page, and your dog is super cute! I wish you had included a little more info about yourself, but it's cool to see all the places you've been.

**Pull request closed without merging**
