### PR TITLE
Homework 1 - Aysegul Uysal 

### PR DESCRIPTION
**Pull request by ayseguluysal**
This assignment was really helpful to understand how to use GitHub, and clone/commit/push. Initially I had some difficulty locating the folder on my computer that my local files store, but during TA hours with Chelsea I was able to figure out.

### CODE REVIEW

**Review by gmvelez — COMMENTED** [review]
Evaluation HW-01 for Aysegul Uysal
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |       x    |              |            |
| **Coding strategy**         |           |     x         |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |           |     x         |            |
| **Ease of access**          |     x      |              |            |

This is a good job using some different formatting with R Markdown and presenting a little bio for yourself.  As a couple of notes, the reflection could have been a little more developed to talk about the practice, and you could have incorporated a link.  The image was a good job, but another way you can do it if you want is to save the image in the same folder that you have the markdown and then you would just link to it (i.e. .  Then the image would also be pushed to Git and end up in your pull request and as part of the document.

**Comment by marieakerman** [comment]
Evaluation HW-01 for Aysegul Uysal
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |    x       |              |            |
| **Achievement, creativity** |      x     |              |            |
| **Ease of access**          |     x      |              |            |

Remarks:

* Nice work! The biography looks nice and reads clearly. You included a variety of elements, including headers, an image, bullet points, and bold/italics.
* Including a link would have been nice, but you included all the other elements.

**Review by marieakerman — COMMENTED** [review]
Submitting this again because I'm not sure I did it correctly!

Evaluation HW-01 for Aysegul Uysal
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |    x       |              |            |
| **Achievement, creativity** |      x     |              |            |
| **Ease of access**          |     x      |              |            |

Remarks:

* Nice work! The biography looks nice and reads clearly. You included a variety of elements, including headers, an image, bullet points, and bold/italics.
* Including a link would have been nice, but you included all the other elements.

**Comment by DanielKLowery** [comment]
Evaluation HW-01 for Aysegul Uysal
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x     |              |            |
| **Coding strategy**         |           |      x       |            |
| **Presentation**            |      x    |              |            |
| **Achievement, creativity** |           |       x      |            |
| **Ease of access**          |     x     |              |            |

Remarks:
First, your small research snippet was very interesting! This assignment was pretty light on code, but you did a good job with code required. There is the one issue with the photos already raised in a previous review. The major thing I found lacking was explanation on how you edited the README.md file. Did you edit it on Github? In an R script? Did you sync R with Github? I also had a bit of trouble with the whole push/pull Git work.

**Pull request closed without merging**
