### PR TITLE
HW01-Jingyi Lu

### PR DESCRIPTION
**Pull request by jingyi22**
First of all, I installed the software of Github. Then I got the code README.md from uc-cfss by forking it to my own account and I got a file in my local Github folder. Second, I opened this file in RStudio and began to edit it. I read the instructions on Markdown language and wrote the text with the codes of “headers”,”emphasis”,”lists”,”images” and “links.” To add images, I uploaded a image to my GitHub platform and got a image link and then I pasted the link to the text. After finishing writing all the items, I saved the changes which are automatically synchronous with those on the GitHub. Finally, I created a pull request and submitted.

### CODE REVIEW

**Comment by cwfowler** [comment]
I was not requested to review anyone's assignment so I am randomly choosing two as was instructed. Moving on, I think this was a great job on this assignment. Headers were properly done and all required elements were included: italicized and bolded text, a list, and a link. As well, the info is presented in a clear and concise manner. Overall, I have no negative critique to offer. Great job!

**Review by lmulholland42 — COMMENTED** [review]
Evaluation HW-01 for Jingyi Lu

Coding style: Excellent
Coding strategy: Excellent
Presentation: Excellent
Achievement, creativity: Excellent
Ease of access: Excellent


Remarks
Overall the coding is very clear and the README file is very well formatted. I like that you did all of the different formatting options, like using headers, bold text, etc. There wasn't a lot of information, but it was well presented.

**Comment by nnickels** [comment]
Evaluation HW-01 for Jingyi Lu
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     X      |              |            |
| **Coding strategy**         |     X      |              |            |
| **Presentation**            |     X      |              |            |
| **Achievement, creativity** |           |      X       |            |
| **Ease of access**          |     X      |              |            |

Remarks:

* Great job on the first homework - you display multiple elements of markdown and your README renders clean and neat.
* Good work saving a photo in your repo and calling it via the jpg title!

**Review by nnickels — COMMENTED** [review]
Evaluation HW-01 for Jingyi Lu
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     X      |              |            |
| **Coding strategy**         |     X      |              |            |
| **Presentation**            |     X      |              |            |
| **Achievement, creativity** |           |      X       |            |
| **Ease of access**          |     X      |              |            |

**Pull request closed without merging**
