### PR TITLE
jeinpark-hw1

### PR DESCRIPTION
**Pull request by jeinpark**
Homework 1 turned out to be more tedious than I anticipated it to be, but it was not extremely difficult. One of the TA’s explained to me what pulling and forking a repo means, and guided me towards getting hw 1’s repository into my R Studio. 

I started off by reading the R markdown cheatsheet (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) and wrote a basic bio of myself. I didn’t encounter any problems setting the header, bold, and italics but once I finished a basic bio, I wasn’t sure how to view the final result.

I asked my friend how I could view the result and she told me to press preview (a rookie mistake). It turns out that none of the bullets or links were showing up in the way they should and my friend tried to explain some of my issues, but in R markdown. When we both realized that I was supposed to use Markdown instead of R markdown, I was left to my own devices because she was only used to using R markdown. 

The bullet points and links weren’t cooperating so I called it a day and decided to come back to the issue another time. When I was ready, I did a lot of google searching and realized that I wasn’t putting spaces between my bullet texts, which is why my asterisks were showing up as regular asterisks in plain text format. So I fixed that, but my links were still not working. I did more google searching and found out I got some of the syntax wrong, such as putting brackets where there should be parenthesis and vice versa. 

Lastly, my image embed wasn’t working either until I realized that I provided the link to the image on the internet instead of providing the html image link. Once I fixed that, I made it left-aligned and completed homework 1. I used StackExchange and GitHub for most of the questions I googled.

### CODE REVIEW

**Review by amandaroseb — COMMENTED** [review]
The page contains a good variety of format displays, such as bolding, italics, bullets, a working link, and a fun image. Well done. 

It looks like there is also a header format for "Biography of Jein Park", though the size of the header makes it look about the same size as the regular text, just bolded. I might suggest a bigger header size (maybe using two ## instead of four ####) to make the section title stand out. Also, it may not have been necessary to keep the "Repository for homework 1" text, if the page should function as an introduction to Jein Park. The name of the file already contains hw-1. 

I noticed that you also learned how to left-justify your image in the markdown code. I didn't know how to do that myself, and am glad to learn!

**Comment by cernhofer** [comment]
Evaluation HW-01 for Jein Park
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      x     |              |            |
| **Coding strategy**         |     x      |              |            |
| **Presentation**            |     x      |              |            |
| **Achievement, creativity** |           |      x        |            |
| **Ease of access**          |      x     |              |            |

* Great job! Your readme looks great and you've used a number of markdown elements.

**Comment by cscrivner** [comment]
Topic | Excellent | Satisfactory | Needs work
-- | -- | -- | --
Coding Style | X |   |  
Coding Strategy | X |   |  
Presentation | X |   |  
Achievement,   Creativity |   | X |  
Ease of Access | X |   |  

Remarks:

Great job on your bio! Looks like you used all of the markdowns and your presentation is done well. Perhaps most impressive was your perseverance! Great job looking up how to fix issues you had and taking a break to clear your head when you had been working on it for a while. If this is any indication of your general work ethic, you'll be great at coding!

**Review by cscrivner — COMMENTED** [review]
Topic | Excellent | Satisfactory | Needs work
-- | -- | -- | --
Coding Style | X |   |  
Coding Strategy | X |   |  
Presentation | X |   |  
Achievement,   Creativity |   | X |  
Ease of Access | X |   |  

Remarks:

Great job on your bio! Looks like you used all of the markdowns and your presentation is done well. Perhaps most impressive was your perseverance! Great job looking up how to fix issues you had and taking a break to clear your head when you had been working on it for a while. If this is any indication of your general work ethic, you'll be great at coding!

**Pull request closed without merging**
